[package]
name = "graphql_client_cli"
version = "0.1.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]
license = "Apache-2.0 OR MIT"

[[bin]]
name = "graphql-client"
path = "src/main.rs"

[dependencies]
failure = "0.1"
reqwest = "0.8"
graphql_client = { version = "0.1.0", path = ".." }
structopt = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
