[package]
name = "graphql_query_github_example"
version = "0.1.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]

[dependencies]
failure = "*"
graphql_client = { path = "../.." }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "*"
prettytable-rs = "0.7.0"
structopt = "0.2.10"
dotenv = "0.13.0"
envy = "0.3.2"
